import Head from "next/head";
import {
  Box,
  Container,
  Typography,
} from "@mui/material";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Research Funding DApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Navbar/>
        <Container
          maxWidth="lg"
          sx={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            height: "90vh",
          }}
        >
          <Box mt={-15}>
            <Typography variant="h2" align="center" color='black'>
              Fund Your Research Startup
            </Typography>
            <Typography variant="h5" align="center" color="gray" >
              Research, Innovate, Make and Produce with Crypto Funding.
            </Typography>
          </Box>
          <img
            src="./researcher.png"
            alt="Home_Image"
            style={{ width: "60%", height: "80%", objectFit:'cover' }}
          />
        </Container>
      </Box>
    </div>
  );
}
